CREATE TABLE sys_org (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   NUMBER(19) DEFAULT 0 NOT NULL,
    org_name    VARCHAR2(128) NOT NULL,
    org_code    VARCHAR2(64) NOT NULL,
    sort_order  NUMBER(10) DEFAULT 0 NOT NULL,
    status      NUMBER(10) DEFAULT 1 NOT NULL,
    created_at  VARCHAR2(32) NOT NULL,
    updated_at  VARCHAR2(32) NOT NULL,
    CONSTRAINT uk_sys_org_code UNIQUE (org_code)
);

CREATE INDEX idx_sys_org_parent_id ON sys_org (parent_id);
