CREATE TABLE sys_user (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          NUMBER(19),
    username        VARCHAR2(64) NOT NULL,
    password        VARCHAR2(128) NOT NULL,
    nickname        VARCHAR2(64),
    status          NUMBER(10) DEFAULT 1 NOT NULL,
    is_super_admin  NUMBER(10) DEFAULT 0 NOT NULL,
    created_at      VARCHAR2(32) NOT NULL,
    updated_at      VARCHAR2(32) NOT NULL,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

CREATE INDEX idx_sys_user_org_id ON sys_user (org_id);
