CREATE TABLE sys_role (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   VARCHAR2(64) NOT NULL,
    role_name   VARCHAR2(64) NOT NULL,
    status      NUMBER(10) DEFAULT 1 NOT NULL,
    remark      VARCHAR2(255),
    created_at  VARCHAR2(32) NOT NULL,
    updated_at  VARCHAR2(32) NOT NULL,
    CONSTRAINT uk_sys_role_code UNIQUE (role_code)
);
