CREATE TABLE sys_menu (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   NUMBER(19) DEFAULT 0 NOT NULL,
    menu_name   VARCHAR2(64) NOT NULL,
    menu_type   VARCHAR2(16) NOT NULL,
    path        VARCHAR2(128),
    component   VARCHAR2(64),
    icon        VARCHAR2(64),
    sort_order  NUMBER(10) DEFAULT 0 NOT NULL,
    visible     NUMBER(10) DEFAULT 1 NOT NULL,
    status      NUMBER(10) DEFAULT 1 NOT NULL,
    created_at  VARCHAR2(32) NOT NULL,
    updated_at  VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);
