CREATE TABLE sys_oper_log (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19),
    username        VARCHAR2(64),
    module_name     VARCHAR2(64) NOT NULL,
    menu_name       VARCHAR2(64),
    oper_type       VARCHAR2(32) NOT NULL,
    oper_desc       VARCHAR2(512) NOT NULL,
    request_uri     VARCHAR2(255),
    request_method  VARCHAR2(16),
    client_ip       VARCHAR2(64),
    status          NUMBER(10) DEFAULT 1 NOT NULL,
    error_message   VARCHAR2(512),
    created_at      VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_sys_oper_log_created_at ON sys_oper_log (created_at);
CREATE INDEX idx_sys_oper_log_username ON sys_oper_log (username);
CREATE INDEX idx_sys_oper_log_oper_type ON sys_oper_log (oper_type);
