CREATE TABLE access_log (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ip       VARCHAR2(64) NOT NULL,
    http_method     VARCHAR2(16) NOT NULL,
    request_uri     VARCHAR2(255) NOT NULL,
    response_status NUMBER(10),
    cost_ms         NUMBER(19),
    log_type        VARCHAR2(32) NOT NULL,
    error_message   VARCHAR2(512),
    created_at      VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_access_log_created_at ON access_log (created_at);

CREATE TABLE mail_send_log (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ip     VARCHAR2(64),
    sender        VARCHAR2(128),
    recipient     VARCHAR2(128) NOT NULL,
    subject       VARCHAR2(255) NOT NULL,
    content       CLOB,
    status        VARCHAR2(32) NOT NULL,
    error_message VARCHAR2(512),
    created_at    VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_mail_send_log_created_at ON mail_send_log (created_at);

CREATE TABLE ruankao_scan_log (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ip       VARCHAR2(64),
    trigger_type    VARCHAR2(32) NOT NULL,
    matched         NUMBER(10) NOT NULL,
    email_sent      NUMBER(10) NOT NULL,
    message         VARCHAR2(512),
    matched_titles  CLOB,
    status          VARCHAR2(32) NOT NULL,
    error_message   VARCHAR2(512),
    created_at      VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_ruankao_scan_log_created_at ON ruankao_scan_log (created_at);

CREATE TABLE system_event_log (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_level  VARCHAR2(16) NOT NULL,
    category   VARCHAR2(32) NOT NULL,
    message    VARCHAR2(512) NOT NULL,
    detail     CLOB,
    created_at VARCHAR2(32) NOT NULL
);

CREATE INDEX idx_system_event_log_created_at ON system_event_log (created_at);
