#!/bin/bash

APP=${APP:-/app}
MAILCURSOR_HOME=${MAILCURSOR_HOME:-$APP/mailcursor}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

JAVA_HOME=${JAVA_HOME:-$APP/jdk}
JAR_NAME=MailCursor-1.0.0-SNAPSHOT.jar
JAR_PATH=$MAILCURSOR_HOME/$JAR_NAME
CONFIG_DIR=$MAILCURSOR_HOME/config
DATA_DIR=$MAILCURSOR_HOME/data
BACKUP_DIR=$MAILCURSOR_HOME/backup
LOG_DIR=$MAILCURSOR_HOME/logs
PID_FILE=$LOG_DIR/app.pid
HEALTH_URL=${HEALTH_URL:-http://127.0.0.1:8080/api/ruankao/scan}
STARTUP_WAIT_SECONDS=${STARTUP_WAIT_SECONDS:-12}

export JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
export LANG=${LANG:-C.UTF-8}
export LC_ALL=${LC_ALL:-C.UTF-8}
export PYTHONIOENCODING=utf-8
